name: 'Deploy test DB server'

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  WITH_SSH: 'ssh -o StrictHostKeyChecking=no -i ./rsa_id -p ${{ secrets.TEST_SERVER_SSH_PORT }} ${{ secrets.TEST_SERVER_SSH_USERNAME }}@${{ secrets.TEST_SERVER_SSH_URL }}'

jobs:
  deploy:
    name: 'Deploy test DB server'
    runs-on: ubuntu-latest

    steps:
      - name: 'Get SSH key'
        run: |
          echo "${{ secrets.TEST_SERVER_SSH_KEY }}" > ./rsa_id
          chmod 600 ./rsa_id
      
      - name: 'Stop exist DB server'
        run: |
          ${{ env.WITH_SSH }} "cd ~/DB && docker-compose -f test-server.compose.yml down"

      - name: 'Pull latest code'
        if: always()
        run: |
          ${{ env.WITH_SSH }} "cd ~/DB && git pull origin main"
      
      - name: 'Set environment variables'
        if: always()
        run: |
          echo "MYSQL_PORT=${{ secrets.TEST_SERVER_DB_PORT }}" > .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.TEST_SERVER_DB_ROOT_PW }}" >> .env
          echo "MYSQL_USER=${{ secrets.TEST_SERVER_DB_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.TEST_SERVER_DB_PW }}" >> .env
      
          scp -o StrictHostKeyChecking=no -i ./rsa_id -P ${{ secrets.TEST_SERVER_SSH_PORT }} .env ${{ secrets.TEST_SERVER_SSH_USERNAME }}@${{ secrets.TEST_SERVER_SSH_URL }}:~/DB/.env

      - name: 'Start DB server'
        if: always()
        run: |
          echo "cd ~/DB && docker-compose -f test-server.compose.yml --env-file .env up -d" >> ./run.sh

          ${{ env.WITH_SSH }} "bash -s" < ./run.sh